### ISSUE TITLE
Accessibility: The Cursor Will Focused at the end of Editor Content When Open Voice Over on iPhone

### ISSUE THREAD

**Issue by Li-Wanjing** [microsoft/roosterjs#1803] opened 2023-05-17 04:43 UTC
**Describe the bug**
The Cursor Will Focused at the end of Editor Content When Open Voice Over on iPhone

**To Reproduce**
1. Open RoosterJS sample in Safari on iOS
2. Type some text int the editor
3. Go to the Settings -> Accessibility -> Voice Over -> turn on the Voiceover item.
4. Back to Safari with RoosterJS sample
5. Single tap the editor area, and double tap to focus on it.

**Expected behavior**
The cursor should be shown in first position.

**Screenshots**

**Device Information**
 - OS: iOS 16.4.1
 - Browser: Safari
 - Version 16.4.1

**Additional context**
repro video:

https://github.com/microsoft/roosterjs/assets/11981186/89c22e68-329c-446c-b86b-aef5b2578da2

**Comment by JiuqingSong** [comment] 2023-05-18 15:36
I believe this is by design. And in order to change selection with VoiceOver, need to turn this feature on in iPhone and use the rotor to change selection mode to TextSelection. Please refer to https://www.youtube.com/watch?v=BbpK8sgxY_c

**Comment by Li-Wanjing** [comment] 2023-05-22 03:13
At first I thought it is by design as well, but then I tried to load a html only contain a content editable div in Safari, the cursor in that div won't be focused on the end position.

https://github.com/microsoft/roosterjs/assets/11981186/d7c0d14d-8c7e-42fb-a26c-fe054b5c4a04

**Comment by JiuqingSong** [comment] 2023-05-22 16:51
Hmm ok, possibly related to https://github.com/microsoft/roosterjs/issues/1124

Do you want to submit a fix? I guess if we just add an option to disable restoring selection, maybe this can be fixed.

**Comment by Li-Wanjing** [comment] 2023-05-23 02:24
Sure! Let me verify it first.

**Comment by JiuqingSong** [comment] 2023-07-04 04:28
Hi @Li-Wanjing , do you want to submit a fix? Or I'll close this issue for now since we don't plan to fix it from our side. Thanks

**Closed** 2023-07-10 04:56 UTC
