### ISSUE TITLE
Copy and paste preserves source formatting differently in different situations

### ISSUE THREAD

**Issue by pemj** [microsoft/roosterjs#352] opened 2019-08-29 18:29 UTC
I've got a work item in azure devops, the acceptance criteria of which I'm in the process of editing (using firefox). The contents of the editor window are a mix of bold and non-bold text, like so:
1. Edit yaml file **(then check logs)**
2. Determine next course of action **(Verify throughput)**

If I copy line 1, and insert it in between two bold words in line 2, I would expect the following:
1. Edit yaml file **(then check logs)**
2. Determine next course of action **(Verify**  1. Edit yaml file **(then check logs)** **throughput)**

However, instead the bold style is inherited from the existing location, producing the following:
1. Edit yaml file **(then check logs)**
2. Determine next course of action **(Verify  1. Edit yaml file (then check logs) throughput)**

Which, fair enough, I guess that makes a sort of sense, different programs treat paste differently, my conclusion was then that any text pasted to a particular location inherits the style of that location.

If that were the case, then copying line 1 and inserting it into line 2 between two non-bold lines should produce non-bold text like so:
1. Edit yaml file **(then check logs)**
2. Determine next 1. Edit yaml file (then check logs) course of action **(Verify throughput)**

However, it does not. Instead, it produces the following:
1. Edit yaml file **(then check logs)**
2. Determine next 1. Edit yaml file **(then check logs)** course of action **(Verify throughput)**

This seems to indicate that the style of the target isn't always inherited, but rather that style is selectively inherited, in a way that doesn't make a ton of sense to me. Is this behavior documented anywhere, or expected?

To exacerbate the issue, it seems like the bold style is actually being applied multiple times in some cases, and thus I end up with multiple bold regions that look different degrees of bold, like so:
![image](https://user-images.githubusercontent.com/4634313/63966432-1fba2c80-ca50-11e9-8f9b-a55ca745236c.png)
I can make them look the same by toggling bold off and on again, so there's a workaround to fix the text, but I don't know exactly how to prevent it.

**Comment by JiuqingSong** [comment] 2019-08-29 23:43
Tried and I can repro in Firefox. However, it seems the issue is the copy behavior of Firefox, but not paste.

In Firefox, this it what copied to clipboard:

```html
<html><body> <!--StartFragment-->Edit yaml file<span> </span><strong style="box-sizing: border-box; font-weight: 600">(then check logs)</strong><!--EndFragment--> </body> </html>
```

You can see that there isn't any format info for "Edit yaml file", so when paste, it will just inherit the current format. 

Compare to Chrome, this is what are copied:

```html
<html>
 <body>
 <!--StartFragment--><ol style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><li>Edit yaml file (<b>then check logs)</b></li></ol><!--EndFragment-->
 </body>
 </html>
```

You can see there are very rich format info so we can preserve its format when paste

**Comment by pemj** [comment] 2019-08-30 17:54
Where are you copying the text from? If I copy that text above directly from github (using firefox), what I get does indeed just look like this:
```
<html><body>
<!--StartFragment-->Edit yaml file <strong>(then check logs)</strong><!--EndFragment-->
</body>
</html>
```

But if I copy the text from an editor window on an azure devops work item, I see this:
```
<html><body>
<!--StartFragment--><span>edit yaml file <b>(then check logs)</b></span><!--EndFragment-->
</body>
</html>
```

That aside, I actually just checked this on chrome and reproduced the issue. As rich and specific as the formatting may be, it isn't preserved through copy and paste there either. Copying the following text with chrome:
<html>
<body>
<ul style="box-sizing: border-box; padding: 0px 0px 0px 40px; color: rgba(0, 0, 0, 0.9); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; list-style: inherit;">edit yaml file<span> </span><b style="box-sizing: border-box;">(then check logs)</b></li></ul>
</body>
</html>

Gives me the following html:

```
<html>
<body>
<!--StartFragment--><ul style="box-sizing: border-box; padding: 0px 0px 0px 40px; color: rgba(0, 0, 0, 0.9); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; list-style: inherit;">edit yaml file<span> </span><b style="box-sizing: border-box;">(then check logs)</b></li></ul><!--EndFragment-->
</body>
</html>
```
Lot of details. If I copy that text and paste it into the bold section of itself, I get this:
<html>
<body>
<ul style="box-sizing: border-box; padding: 0px 0px 0px 40px; color: rgba(0, 0, 0, 0.9); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; list-style: inherit;">edit yaml file<span> </span><b style="box-sizing: border-box;">(then cheedit yaml file<span style="box-sizing: border-box;"> </span><b style="box-sizing: border-box;">(then check logs)</b>ck logs)</b></li></ul>
</body>
</html>
The HTML for that, also very rich, looks like this:

```
<html>
<body>
<!--StartFragment--><ul style="box-sizing: border-box; padding: 0px 0px 0px 40px; color: rgba(0, 0, 0, 0.9); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; list-style: inherit;">edit yaml file<span> </span><b style="box-sizing: border-box;">(then cheedit yaml file<span style="box-sizing: border-box;"> </span><b style="box-sizing: border-box;">(then check logs)</b>ck logs)</b></li></ul><!--EndFragment-->
</body>
</html>
```

With regard to the double-bolding behavior, I can't actually reproduce that effect in this text box, since github doesn't render the text as double-bold, but the HTML copied via firefox looks like this:
```
<html><body>
<!--StartFragment--><span>edit yaml file <b>(then che<span>edit yaml file <b>(then check logs)</b></span>ck logs)</b></span><!--EndFragment-->
</body>
</html>
```

Note, it looks the same if I copy the text from chrome into firefox and then copy that text. If I copy the text from firefox into chrome, I get the same richly formatted html, with nested bold tags (`<b style="box-sizing: border-box;">(then cheedit yaml file<span style="box-sizing: border-box;"> </span><b style="box-sizing: border-box;">(then check logs)</b>ck logs)</b>`), except that chrome doesn't render it as extra bold.

**Comment by pemj** [comment] 2019-08-30 21:18
I checked a few other places, I can't replicate the double-bold display behavior in firefox except in roosterjs. In fact, I actually can't even reproduce it in the roosterjs playground outside of azure devops. I can break the "renders nested bold tags as extra-bold in firefox" situation into a separate issue if you like, or we could see if devops is using an out-of-date version that they need to update.

**Comment by JiuqingSong** [comment] 2019-08-30 23:48
In most cases, when paste we just insert the copied tags (after some kind of process) to current position. However, if there is format tags like B, I, U, STRONG, FONT, ... and the inserted node doesn't contain any default format, the formats from parent tags will be inherited. It is hard to say what we should keep and what we should remove, since the copied content doesn't contain enough information. Just like if you copy some plain text (e.g. from notepad) and paste, all parent formats will be inherited.

We can split any existing format tags, and insert the pasted nodes outside them. for example
```html
<B><I>Hello world</I></B>
```
When paste between hello and world, we can first split the tags to:
```html
<B><I>Hello</I></B><B><I>world</I></B>
```
Then paste like this:
```html
<B><I>Hello</I></B>[Pasted Content]<B><I>world</I></B>
```

But there is still question: what format should pasted content be? If we don't specify any format, it will just use whatever format specified outside of editor, which is totally out of control.

Furthermore, what if there is some format specified by <SPAN> or any other tag, say
```html
<SPAN style="font-weight: 600">...</SPAN>
```
Should we inherit this format?

So I think the best behavior will be just keep it as it is, and user can do any change they want after paste.

For the double bold thing, it is caused by the same reason, but we can mitigate it by checking if we are already in the same tag for tags like B. I, U, STRONG, ... and ignore the inner one.

**Comment by JiuqingSong** [comment] 2019-12-28 22:54
Close old issues.

**Closed by JiuqingSong** 2019-12-28 22:54 UTC
