### ISSUE TITLE
createLink() function replaces the existing content

### ISSUE THREAD

**Issue by codingwithdream** [microsoft/roosterjs#1639] opened 2023-03-15 03:45 UTC
**Describe the bug**
Insert a link with a block display and then insert a br after the link. When putting the cursor in the br, it will replace the inserted link.

**To Reproduce**
1. Go to the test https://codepen.io/dreamxcf/pen/eYjGxWb
2. Click on `Insert Block Anchor` button, '**A block anchor 1**' is inserted
![image](https://user-images.githubusercontent.com/69707749/225199847-40caa427-6c8c-4c39-b845-f939b88bb8f8.png)
3. Put the cursor in the next line of the inserted link
![image](https://user-images.githubusercontent.com/69707749/225200693-574b5372-3c26-48d1-8500-2503c5b2db0c.png)

4. Click on `Insert Normal Anchor` button, the '**A block anchor 1**' is replaced as '**A normal anchor 2**'

**Expected behavior**
'**A normal anchor 2**' is inserted in the next line of '**A block anchor 1**'
<img width="372" alt="image" src="https://user-images.githubusercontent.com/69707749/225200804-7923d9cb-6640-4c9b-ac40-a75b799a3b17.png">

**Actual behavior**
<img width="372" alt="image" src="https://user-images.githubusercontent.com/69707749/225200530-3dbf30e0-57b3-4bef-bee9-79fc9df394f0.png">

**Device Information**
 - Browser: chrome

**Comment by JiuqingSong** [comment] 2023-03-18 23:39
This is now fixed by content model. You can consider use the new API https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-content-model/lib/publicApi/link/insertLink.ts together with new Content Model Editor https://github.com/microsoft/roosterjs/blob/master/packages/roosterjs-content-model/lib/editor/ContentModelEditor.ts which is compatible with original editor.

**Closed** 2023-03-20 18:47 UTC
Labels: ContentModel

**Comment by codingwithdream** [comment] 2023-03-21 08:06
I have two questions about the new API:
(1) Is the new "insertLink" API rolling out or rolled out completely? 
(2) Could we replace the original "createLink" API (from `roosterjs-editor-api`) with the new `insertLink` API completely now?

**Comment by codingwithdream** [comment] 2023-03-22 05:47
> I have two questions about the new API: (1) Is the new "insertLink" API rolling out or rolled out completely? (2) Could we replace the original "createLink" API (from `roosterjs-editor-api`) with the new `insertLink` API completely now?

@JiuqingSong @romanisa Could you help answer? Thanks

**Comment by JiuqingSong** [comment] 2023-03-22 06:53
We are still improving content model. For this API itself is relatively stable now.

The original bug is caused by a very low level API. The fix will be risky since it may cause other more serious bugs.

If you don't want to use Content Model for now, you can create your own createLink() API since all its used are public API, so you can write you own API to replace it.
