### ISSUE TITLE
Lazy loading for image in content

### ISSUE THREAD

**Issue by pddt1** [microsoft/roosterjs#1177] opened 2022-08-13 18:34 UTC
I want to add react component ( from library ) for images but I see that the initialContent option is a string HTML.
Can I use lazy loading library for image in the content? but not using loading attribute.

**Comment by JiuqingSong** [comment] 2022-08-15 03:49
Please refer to EditorReady event https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_editor_types.editorreadyevent.html

**Comment by pddt1** [comment] 2022-08-15 07:53
> Please refer to EditorReady event https://microsoft.github.io/roosterjs/docs/interfaces/roosterjs_editor_types.editorreadyevent.html

Tks u for reply but i don't see how i can add React element to content.

**Comment by JiuqingSong** [comment] 2022-08-15 16:18
There is no direct support to add react component. You need to use ReactDOM.render(...) to render it and manage the react component lifecycle (e.g. when user use DELETE or BACKSPACE key to delete the component, you also need to unmount it to avoid memory leak). So generally it is not recommended to render a react component into an editable container since the content is not only controlled by your code, but also by user's action.
________________________________

**Comment by jvillalobos** [comment] 2022-08-22 18:12
Closing this as this is by design at the moment.

**Closed by jvillalobos** 2022-08-22 18:12 UTC
