### ISSUE TITLE
On firefox, numbering happens incorrectly

### ISSUE THREAD

**Issue by bochong** [microsoft/roosterjs#329] opened 2019-07-29 17:08 UTC
@JiuqingSong Could you take a look? I've attached a gif below. Thanks
![ErrorInFirxfox](https://user-images.githubusercontent.com/42078122/62067449-a2995e80-b1e8-11e9-8b61-af7178225a4b.gif)

**Comment by JiuqingSong** [comment] 2019-08-01 23:26
Opened Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1570809

It not only happens in editor, but also for a regular list.

**Comment by pemj** [comment] 2019-08-29 18:06
That bug is marked as a duplicate of the following bug, which appears to indicate that this issue only appears when invalid markup is used. As long as the firefox team is deliberating on whether to "fix" this functionality, should we just, make sure we're using valid markup?
https://bugzilla.mozilla.org/show_bug.cgi?id=1548753

**Comment by pemj** [comment] 2019-08-30 21:49
Ran a quick check, exported the HTML from the list as displayed, looked at it in a text editor, edited the inner UL/OL tags to be nested inside of LI tags as the HTML spec requires, and it formats the numbers correctly. 

Version as displayed in roosterJS playground:
<ol><li>a</li><li>a</li><li>a<br></li><ol><li>a</li></ol><li>a<br></li></ol>
generated by the following source:


```
<ol>
	<li>a</li>
	<li>a</li>
	<li>a<br></li>
	<ol>
		<li>a</li>
	</ol>
	<li>a<br></li>
</ol>
```

Now if I go through and change where those `</li>` tags end, we get the correct numerical ordering:
<ol>
	<li>a</li>
	<li>a</li>
	<li>a<br>
	<ol>
		<li>a</li>
	</ol></li>
	<li>a<br></li>
</ol>
As generated by this source:

```
<ol>
	<li>a</li>
	<li>a</li>
	<li>a<br>
	<ol>
		<li>a</li>
	</ol></li>
	<li>a<br></li>
</ol>
```

**Comment by pemj** [comment] 2019-09-09 18:09
Oh. This library drops down to execCommand() for indentation. That makes this more complicated, yeah. Given the official word regarding execCommand() (see image below, sourced from the [execCommand spec](http://w3c.github.io/editing/execCommand.html)), do you happen to know if there's any support for refactoring this library to remove the use of execCommand() in cases where it's possible?
![image](https://user-images.githubusercontent.com/4634313/64555339-f91eb000-d2f1-11e9-874e-be1b3efa49d2.png)

**Comment by JiuqingSong** [comment] 2019-09-09 18:59
Although execCommand is marked as deprecated, I still think Firefox should fix their bug since is a regression. However, it seems this may not be fixed very soon, or maybe never. So I think we need to consider having our own method of indent/outdent.

I'll priorities this one and try to build a new version of setIndentation API.

**Comment by pemj** [comment] 2019-09-10 22:07
I just built out a nested list in Teams and copied it to a work item editor window, and the numbering on that one works fine. Dumped the HTML, looks like Teams correctly nests OLs inside of LI items, i.e. 
```
<ol>
	<li>Bullet point 1<br></li>
	<li>bullet point 2
		<ol>
			<li>sub-bullet 1</li>
			<li>sub bullet 2</li>
			<li>sub bullet 3</li>
		</ol>
	</li>
	<li>bullet point 3</li>
</ol>
```
They appear to use [ckeditor](https://github.com/ckeditor/ckeditor-dev) without any particularly fancy additions. You can check out ckeditor's list indentation functionality [here](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/indentlist/plugin.js) if you like.

**Comment by bochong** [comment] 2019-10-14 17:46
@JiuqingSong @pemj Will this issue be resolved anytime soon, or is it something firefox will need to fix? I have another feedback ticket from a customer on this bug, but a slightly different scenario. I think it's the same bug though.
![firefoxbug2](https://user-images.githubusercontent.com/42078122/66771670-bbbcbd80-ee6f-11e9-9212-e272aeacc12f.gif)

**Comment by JiuqingSong** [comment] 2020-07-07 17:03
This doesn't happen on firefox 77 now.

**Comment by JiuqingSong** [comment] 2020-07-07 17:14
Hmm, I was wrong. This can still happen.

**Comment by JiuqingSong** [comment] 2020-08-12 07:59
The root Firefox bug is still active: https://bugzilla.mozilla.org/show_bug.cgi?id=1548753

**Comment by pemj** [comment] 2020-08-28 17:13
firefox bug is now closed. Updated firefox instances should soon display incorrect HTML the same way as every other browser.
https://bugzilla.mozilla.org/show_bug.cgi?id=1548753

**Comment by JiuqingSong** [comment] 2020-08-28 17:24
Cool. Let's wait for Firefox 82 see if it can work correctly

**Comment by JiuqingSong** [comment] 2020-09-25 23:10
I verified on Firefox 82.0a1 (2020-09-19) (64-bit) and this is fixed.

**Closed by JiuqingSong** 2020-09-25 23:10 UTC
